"""
Generate iPhone 15 Pro Standard .cube LUT

Bakes the CameraForensicRealism color science pipeline into a portable
33x33x33 3D LUT (.cube format). This lets users apply the iPhone look
via a simple LUT instead of running the full processing pipeline.

Run once:
    python generate_iphone_lut.py

Produces: luts/iPhone_15_Pro_Standard.cube
"""

import numpy as np
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from forensic_engine import (
    apply_iphone_tone_curve,
    apply_p3_color_rendering,
    apply_white_balance,
    apply_blue_shadow_tint,
    apply_highlight_warmth,
)


def generate_iphone_lut(size: int = 33) -> tuple:
    """Generate a 3D LUT by passing a color grid through the iPhone pipeline.

    We use the core color science stages (tone mapping, P3 color, white balance,
    blue shadows, warm highlights) but skip spatial effects (sharpening, noise,
    vignette, local tone mapping, skin detection, deep fusion) since those
    depend on image structure, not just color values.

    Args:
        size: LUT grid size (33 is standard for high-quality LUTs)

    Returns:
        lut: np.ndarray (size, size, size, 3)
    """
    print(f"Generating {size}x{size}x{size} iPhone 15 Pro LUT...")
    t0 = time.time()

    # Create a 1D ramp [0, 1] with `size` steps
    ramp = np.linspace(0.0, 1.0, size, dtype=np.float32)

    # Build the full 3D color grid: (size^3, 3)
    # Order: R changes fastest, then G, then B (cube format standard)
    r, g, b = np.meshgrid(ramp, ramp, ramp, indexing='ij')
    # Reshape to (size, size, size, 3) then to a fake image (size^2, size, 3)
    # so we can process it through the pipeline functions
    grid = np.stack([r, g, b], axis=-1)  # (size, size, size, 3)

    # Flatten to a 2D "image" for processing: (size*size, size, 3)
    flat_h = size * size
    flat_w = size
    img = grid.reshape(flat_h, flat_w, 3)

    # --- Apply color science stages ---
    # These are the stages that depend only on pixel color, not spatial context.
    # Using iPhone 15 Pro Standard defaults at moderate strength.

    # White Balance (iPhone warm daylight bias)
    img = apply_white_balance(img, strength=0.35, temperature=0.25, tint=0.0)

    # Tone Mapping (S-curve with highlight rolloff)
    img = apply_iphone_tone_curve(img, strength=0.42, highlight_rolloff=0.5,
                                   shadow_lift=0.4, contrast=0.5)

    # Display P3 Color Rendering
    img = apply_p3_color_rendering(img, strength=0.35, saturation_boost=0.3,
                                    warmth=0.3)

    # Blue Shadow Tint (iPhone blue-black look)
    img = apply_blue_shadow_tint(img, strength=0.28, shadow_threshold=0.35,
                                  blue_intensity=0.5)

    # Warm Highlights (golden highlight tint)
    img = apply_highlight_warmth(img, strength=0.21, highlight_threshold=0.7,
                                  warmth=0.5)

    # Reshape back to LUT grid
    lut = img.reshape(size, size, size, 3)
    lut = np.clip(lut, 0.0, 1.0).astype(np.float32)

    elapsed = time.time() - t0
    print(f"LUT generated in {elapsed:.2f}s")

    return lut


def write_cube_file(filepath: str, lut: np.ndarray, title: str = "iPhone 15 Pro Standard"):
    """Write a 3D LUT to .cube format.

    Args:
        filepath: Output .cube file path
        lut: np.ndarray (N, N, N, 3) with values in [0, 1]
        title: LUT title string
    """
    n = lut.shape[0]
    os.makedirs(os.path.dirname(filepath), exist_ok=True)

    with open(filepath, 'w') as f:
        f.write(f'# Generated by ComfyUI-CameraForensicRealism\n')
        f.write(f'# iPhone 15 Pro ISP Color Science LUT\n')
        f.write(f'TITLE "{title}"\n')
        f.write(f'LUT_3D_SIZE {n}\n')
        f.write(f'DOMAIN_MIN 0.0 0.0 0.0\n')
        f.write(f'DOMAIN_MAX 1.0 1.0 1.0\n')
        f.write(f'\n')

        # Write data in R-fastest order (standard .cube ordering)
        for bi in range(n):
            for gi in range(n):
                for ri in range(n):
                    r, g, b = lut[bi, gi, ri]
                    f.write(f'{r:.6f} {g:.6f} {b:.6f}\n')

    size_kb = os.path.getsize(filepath) / 1024
    print(f"Written: {filepath} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    lut_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "luts")
    out_path = os.path.join(lut_dir, "iPhone_15_Pro_Standard.cube")

    lut = generate_iphone_lut(size=33)
    write_cube_file(out_path, lut, title="iPhone 15 Pro Standard")

    print("\nDone! LUT file ready for use.")
